# Generated by Django 5.1.6 on 2025-03-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#FF5733', 'Red'), ('#33FF57', 'Green'), ('#3357FF', 'Blue'), ('#FF33A8', 'Pink'), ('#FFC300', 'Yellow'), ('#A833FF', 'Purple'), ('#33FFF3', 'Cyan')], default='#FF5733', max_length=7),
        ),
    ]
